### ISSUE TITLE
How to test the trained model ?

### ISSUE THREAD

**Issue by ssbnsk99** [mori97/VaDE#2]

**Comment by mori97** [comment]
The model is tested every epoch during training.
You can find the `test` function in `main.py`.
https://github.com/mori97/VaDE/blob/master/main.py#L34
The classification accuracy and a visualization of the latent space are saved in `runs` directory using Tensorboard.
You can see them with Tensorboard. (If Tensorboard is installed, run `tensorboard --logdir runs`)
(Because Tensorboard will run with reduced feature set if Tensorflow is not installed,
you should install it to see the visualization.)
